"""scripts

Revision ID: 1ebfe8072be6
Revises: 45696d17a671
Create Date: 2017-12-28 16:35:34.549090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ebfe8072be6'
down_revision = '45696d17a671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('server_ip', sa.String(length=15, collation=u'utf8_bin'), nullable=False),
    sa.Column('server_user', sa.String(length=20, collation=u'utf8_bin'), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('server_password', sa.String(length=200), nullable=False),
    sa.Column('scripts_path', sa.Text(collation=u'utf8_bin'), nullable=True),
    sa.Column('scripts_name', sa.Text(collation=u'utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_column(u'users', 'loast_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('loast_login', mysql.DATETIME(), nullable=True))
    op.drop_column(u'users', 'last_login')
    op.drop_table('t_scripts')
    # ### end Alembic commands ###
