version: 1 
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(levelname)s %(module)s-%(lineno)d::%(message)s"

handlers:
    console:
        # class: logging.StreamHandler
        class: swamp.main.libs.liblog.ScreenHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO            
        formatter: simple
        filename: log/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        delay: True
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR            
        formatter: simple
        filename: log/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        delay: True
        encoding: utf8
    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: simple
        filename: log/warning.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        delay: True
        encoding: utf8
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: log/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        delay: True
        encoding: utf8


loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, warning_file_handler, debug_file_handler]